research_cryptocurrency_task:
  description: >
    Conduct a comprehensive analysis of {cryptocurrency_name} using dedicated cryptocurrency data sources (e.g., CoinMarketCap, CoinGecko, CryptoQuant, CoinDCX) and relevant online resources (e.g., project whitepapers, developer blogs). This includes gathering and analyzing the following data:
      Historical Price and Trading Volume: Analyze historical price performance, trading volume trends, and volatility (past 3 years)
      Market Capitalization and Circulating Supply: Assess the cryptocurrency's market position and liquidity.
      Exchange Listings and Trading Activity: Identify major exchanges where the cryptocurrency is traded and analyze trading activity.
      On-chain Transaction Data (if applicable): Analyze on-chain data (e.g., active addresses, transaction volume, fees) to understand network usage and activity.
      Project Development and Roadmap: Evaluate the project's technology, development progress, and future roadmap plans.
      Regulatory Landscape: Identify any relevant regulations or developments that could impact the cryptocurrency.
  expected_output: >
    Prepare a concise research report (3-5 pages) summarizing the following:
      Cryptocurrency Overview and Technology: Describe the underlying technology, functionalities, and purpose of the cryptocurrency.
      Market Performance Analysis: Analyze historical price performance, trading volume trends, and volatility with relevant charts and graphs.
      Network and Project Development Analysis: Discuss the project's development progress, network activity (if applicable), and potential impact on future value.
      Competitive Landscape: Identify key competitors within the same niche or technology and compare their features and market positions.
      Investment Risks and Opportunities: Based on the research findings, identify potential risks (e.g., regulatory changes, competition, technical flaws) and opportunities (e.g., market adoption, future development plans).

analyze_cryptocurrency_task:
  description: >
    Leverage the financial research provided by the Cryptocurrency Researcher to conduct an in-depth analysis of {cryptocurrency_name}.
    Performance Analysis: Analyze the cryptocurrency's performance based on the research findings, focusing on:
      Price volatility and historical trends
      Market capitalization and liquidity compared to other cryptocurrencies
      On-chain data insights (if applicable) for network usage and activity
      Project development progress and potential impact on future value
      Valuation Analysis: Employ appropriate valuation methods for cryptocurrencies (e.g., Network Value to Transaction (NVT) ratio, Stock-to-Flow (S2F) model) to estimate the intrinsic value of {cryptocurrency_name}.
  expected_output: >
    Craft a professional financial report (5-7 pages) with the following sections:
      Executive Summary: Key takeaways and investment thesis
      Cryptocurrency Overview and Technology Description: Briefly describe the underlying technology and functionalities.
      Market Performance Analysis: Analyze historical price performance, trading volume, and volatility with relevant charts and graphs.
      Network and Project Development Analysis (including on-chain data insights): Discuss project development progress, network activity (if applicable), and potential impact on future value.
      Valuation Analysis: Explain chosen valuation methods and estimate the intrinsic value of the cryptocurrency.
      Investment Risks and Opportunities: Identify potential risks and opportunities with mitigation strategies based on the analysis.
      Conclusion and Recommendations: Tailor conclusions and recommendations to the target audience (e.g., investors, traders).